[project]
site_name = "STATESPACE"
site_description = "Build AI applications in Markdown"
site_url = "https://docs.statespace.ai"
repo_url = "https://github.com/statespace-tech/statespace"
repo_name = "statespace-tech/statespace"
extra_css = [
  "assets/css/custom.css"
]
extra_javascript = [
  "assets/js/analytics.js",
]
nav = [
  {"Get started" = "index.md"},
  {"Install" = "install.md"},
  {"FAQ" = "faq.md"},
  {"Develop" = [
    {"Pages" = "pages/develop/pages.md"},
    {"Tools" = "pages/develop/tools.md"},
    {"Components" = "pages/develop/components.md"},
  ]},
  {"Deploy" = [
    {"Cloud deployment" = "pages/deploy/cloud.md"},
    {"Self-hosting" = "pages/deploy/self_hosting.md"},
    {"Security" = "pages/deploy/security.md"},
  ]},
  {"Connect" = [
    {"Agents" = "pages/connect/agents.md"},
    {"SSH" = "pages/connect/ssh.md"},
  ]},
  {"Reference" = [
    {"CLI" = "pages/reference/cli.md"},
    {"REST API" = "pages/reference/api.md"},
  ]},
]
copyright = "Copyright &copy; 2026 Statespace Technologies, Inc."

[project.theme]
icon = { repo = "fontawesome/brands/git-alt" }
logo = "assets/images/favicon.svg"
favicon = "assets/images/favicon.svg"
palette = [
  { scheme = "default", primary = "custom", accent = "green", toggle = { icon = "material/lightbulb", name = "Switch to dark mode" } },
  { scheme = "slate", primary = "custom", accent = "green", toggle = { icon = "material/lightbulb", name = "Switch to light mode" } }
]
features = [
  "navigation.footer",
  "navigation.sections",
  "navigation.expand",
  "navigation.top",
  "search.highlight",
  "search.share",
  "content.code.copy",
  "content.code.annotate",
  "navigation.indexes",
  "search.suggest",
  "announce.dismiss",
  "navigation.tracking",
  "navigation.prune",
]

[project.extra]
generator = false

[[project.extra.social]]
  icon = "fontawesome/brands/github"
  link = "https://github.com/statespace-tech/statespace/"
  name = "Star us on GitHub"

[[project.extra.social]]
  icon = "fontawesome/brands/python"
  link = "https://pypi.org/project/statespace/"
  name = "Install from PyPI"

[[project.extra.social]]
  icon = "fontawesome/brands/discord"
  link = "https://discord.gg/rRyM7zkZTf"
  name = "Join our Discord community"

[[project.extra.social]]
  icon = "fontawesome/brands/linkedin"
  link = "https://www.linkedin.com/company/statespace-tech/"
  name = "Follow us on LinkedIn"

[[project.extra.social]]
  icon = "fontawesome/brands/x-twitter"
  link = "https://x.com/statespace_tech"
  name = "Follow us on X (Twitter)"
